import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";
import*as XLSX from"xlsx";

const api=async(u,o={})=>{const t=localStorage.aoc_token;const r=await fetch("/api"+u,{...o,headers:{"Content-Type":"application/json",...(t?{Authorization:"Bearer "+t}:{})}});const d=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem("aoc_token");localStorage.removeItem("aoc_user");window.location.reload()}if(!r.ok)throw Error(d.message||"Request failed");return d};
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2});
const nav=[
 ["dash","Dashboard","⌂"],["entry","New Entry","＋"],["customers","Customers","♙"],["services","Services","▣"],
 ["payments","Payments","₹"],["expenses","Expenses","−"],["stock","Stock","▤"],["reports","Reports","▥"]
];

function Login({done}){const[u,setU]=useState("admin"),[p,setP]=useState(""),[e,setE]=useState(""),[loading,setLoading]=useState(false);return <div className="login"><div className="loginbg"><span/><span/><span/></div><form className="loginbox" onSubmit={async x=>{x.preventDefault();setLoading(true);setE("");try{const d=await api("/login",{method:"POST",body:JSON.stringify({username:u,password:p})});localStorage.aoc_token=d.token;localStorage.aoc_user=JSON.stringify(d.user);done(d.user)}catch(x){setE(x.message)}finally{setLoading(false)}}}><div className="brandmark">AOC</div><h1>Abhi Online Center</h1><p>Management System</p>{e&&<div className="err">{e}</div>}<label>Username<input autoComplete="username" value={u}onChange={e=>setU(e.target.value)}placeholder="Username"/></label><label>Password<input autoComplete="current-password" type="password" value={p}onChange={e=>setP(e.target.value)}placeholder="Password"/></label><button className="primary big" disabled={loading}>{loading?"Logging in…":"Login"}</button></form></div>}

function App(){const[u,setU]=useState(()=>JSON.parse(localStorage.aoc_user||"null")),[p,setP]=useState("dash"),[open,setOpen]=useState(false);if(!u)return <Login done={setU}/>;const title=nav.find(x=>x[0]===p)?.[1]||"Dashboard";const page=p==="dash"?<Dash/>:p==="entry"?<Entry/>:p==="customers"?<Customers/>:p==="services"?<Services/>:p==="payments"?<Payments/>:p==="expenses"?<Expenses/>:p==="stock"?<Stock/>:<Reports/>;return <div className="app"><aside className={open?"mobileOpen":""}><div className="sidebrand"><div className="brandmark small">AOC</div><div><strong>Abhi Online Center</strong><small>Management</small></div><button className="closemenu" onClick={()=>setOpen(false)}>×</button></div><nav>{nav.map(x=><button key={x[0]} className={p===x[0]?"on":""} onClick={()=>{setP(x[0]);setOpen(false)}}><span className="navicon">{x[2]}</span><span>{x[1]}</span></button>)}</nav><button className="logout" onClick={()=>{localStorage.clear();setU(null)}}>↪ <span>Logout</span></button></aside><div className="scrim" onClick={()=>setOpen(false)}/><main><header><button className="hamb" onClick={()=>setOpen(true)}>☰</button><div><b>{title}</b><small>Welcome, {u.username}</small></div><div className="headeruser">{String(u.username||"A").slice(0,1).toUpperCase()}</div></header><div className="content">{page}</div></main><nav className="bottomnav">{nav.slice(0,5).map(x=><button key={x[0]} className={p===x[0]?"on":""} onClick={()=>setP(x[0])}><span>{x[2]}</span><small>{x[1]}</small></button>)}<button onClick={()=>setOpen(true)}><span>☰</span><small>More</small></button></nav></div>}

function Dash(){const[d,setD]=useState(),[busy,setBusy]=useState(true);const load=()=>{setBusy(true);api("/dashboard").then(setD).catch(e=>alert(e.message)).finally(()=>setBusy(false))};useEffect(load,[]);if(busy&&!d)return <Loading/>;const cards=[['Today Sale',money(d?.todaySale)],['Collection',money(d?.todayCollection)],['Entries',d?.todayEntries||0],['Pending',money(d?.pending)],['Expenses',money(d?.todayExpenses)],['Net Collection',money(d?.netCollection)]];const max=Math.max(1,...(d?.trend||[]).map(x=>Number(x.sale||0)));return <><div className="welcome"><div><h1>Good day 👋</h1><p>Today’s business overview and last 7 days activity.</p></div><button className="primary" onClick={load}>↻ Refresh</button></div><div className="cards">{cards.map(x=><div className="card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>Today</small></div>)}</div><div className="dashgrid"><section className="panel"><div className="panelhead"><div><h2>Last 7 Days</h2><p>Sales trend by day</p></div></div><div className="chartbars">{(d?.trend||[]).map(x=><div className="chartcol" key={x._id}><div className="chartbar" style={{height:`${Math.max(6,Number(x.sale||0)/max*150)}px`}} title={`${money(x.sale)} sale`}/><b>{money(x.sale)}</b><small>{new Date(x._id+'T00:00:00').toLocaleDateString('en-IN',{weekday:'short'})}</small></div>)}</div></section><section className="panel"><div className="panelhead"><div><h2>Quick Summary</h2><p>Collection after expenses</p></div></div><div className="summarylist"><div><span>Today's sale</span><b>{money(d?.todaySale)}</b></div><div><span>Today's collection</span><b>{money(d?.todayCollection)}</b></div><div><span>Today's expenses</span><b>{money(d?.todayExpenses)}</b></div><div><span>Net collection</span><b className={(d?.netCollection||0)<0?'dangerText':'successText'}>{money(d?.netCollection)}</b></div></div></section></div><section className="panel"><div className="panelhead"><div><h2>Low Stock</h2><p>Products that need attention</p></div><span className="badge">{d?.lowStock?.length||0} items</span></div><Table h={["Product","Qty","Alert"]} r={(d?.lowStock||[]).map(x=>[x.product,x.quantity,x.lowStockAt])}/></section></>}
function Entry(){
 const[s,setS]=useState([]),[i,setI]=useState([]),[mode,setMode]=useState("service"),
 [custom,setCustom]=useState({work:"",amount:""}),[stock,setStock]=useState([]),
 [f,setF]=useState({customerName:"",mobile:"",operator:"",discount:0,paid:0,paymentMode:"Cash",notes:""}),
 [sel,setSel]=useState(""),[saved,setSaved]=useState(null);
 useEffect(()=>{Promise.all([api("/services"),api("/stock")]).then(([a,b])=>{setS(a);setStock(b)})},[]);
 const sub=i.reduce((a,x)=>a+x.quantity*x.rate,0),tot=Math.max(0,sub-Number(f.discount||0)),pen=Math.max(0,tot-Number(f.paid||0));
 const addService=()=>{const x=s.find(x=>x._id===sel);if(!x)return alert("Please select a service");setI([...i,{name:x.name,type:"Service",quantity:1,rate:Number(x.rate)||0}]);setSel("")};
 const addCustom=()=>{const amount=Number(custom.amount);if(!custom.work.trim())return alert("Custom work name is required");if(!(amount>0))return alert("Enter a valid custom amount");setI([...i,{name:custom.work.trim(),type:"Custom",quantity:1,rate:amount}]);setCustom({work:"",amount:""})};
 const addStock=()=>{const x=stock.find(x=>x._id===sel);if(!x)return alert("Please select a stock product");if(Number(x.quantity)<=0)return alert("This product is out of stock");setI([...i,{name:x.product,type:"Stock",stockId:x._id,quantity:1,rate:Number(x.sellingPrice)||0}]);setSel("")};
 const save=async()=>{if(!f.customerName.trim())return alert("Customer name is required");if(!i.length)return alert("Please add at least one service or custom work");try{const x=await api("/transactions",{method:"POST",body:JSON.stringify({...f,items:i})});setSaved(x);setI([]);setF({...f,discount:0,paid:0,notes:""});}catch(e){alert(e.message)}};
 return <section className="panel">
  <div className="panelhead"><div><h2>New Entry / Billing</h2><p>Add normal services or enter any custom work manually.</p></div>{saved&&<div className="saved"><b>{saved.invoiceNo}</b><button onClick={()=>printInvoice(saved,"a4")}>A4</button><button onClick={()=>printInvoice(saved,"thermal")}>Thermal</button></div>}</div>
  <div className="sectiontitle">Customer Details</div>
  <div className="grid"><Field label="Customer Name" value={f.customerName} onChange={v=>setF({...f,customerName:v})}/><Field label="Mobile Number" value={f.mobile} onChange={v=>setF({...f,mobile:v})} inputMode="numeric"/><Field label="Operator" value={f.operator} onChange={v=>setF({...f,operator:v})}/></div>
  <div className="sectiontitle">Add Work / Service</div>
  <div className="entrymodes"><button className={mode==="service"?"modebtn active":"modebtn"} onClick={()=>setMode("service")}>▣ Existing Service</button><button className={mode==="custom"?"modebtn active":"modebtn"} onClick={()=>setMode("custom")}>＋ Custom Entry</button><button className={mode==="stock"?"modebtn active":"modebtn"} onClick={()=>setMode("stock")}>▤ Stock Product</button></div>
  {mode==="service"?<div className="addline"><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Select Service</option>{s.filter(x=>x.active).map(x=><option key={x._id} value={x._id}>{x.name} — {money(x.rate)}</option>)}</select><button className="primary" onClick={addService}>＋ Add Service</button></div>:mode==="custom"?<div className="customentry"><Field label="Your Work / Service Name" value={custom.work} onChange={v=>setCustom({...custom,work:v})}/><Field label="Total Amount" type="number" value={custom.amount} onChange={v=>setCustom({...custom,amount:v})}/><button className="primary" onClick={addCustom}>＋ Add Custom Work</button></div>:<div className="addline"><select value={sel} onChange={e=>setSel(e.target.value)}><option value="">Select Stock Product</option>{stock.map(x=><option key={x._id} value={x._id}>{x.product} — {money(x.sellingPrice)} · Stock {x.quantity}</option>)}</select><button className="primary" onClick={addStock}>＋ Add Product</button></div>}
  <Table h={["Item / Work","Type","Qty","Rate","Amount",""]} r={i.map((x,n)=>[x.name,<span className="badge">{x.type||"Service"}</span>,<input className="mini" type="number" min="1" value={x.quantity} onChange={e=>{const a=[...i];a[n]={...a[n],quantity:Math.max(1,+e.target.value)};setI(a)}}/>,money(x.rate),money(x.quantity*x.rate),<button className="iconbtn danger" onClick={()=>setI(i.filter((_,j)=>j!==n))}>×</button>])}/>
  <div className="billbox"><div><span>Subtotal</span><b>{money(sub)}</b></div><label>Discount<input type="number" min="0" value={f.discount} onChange={e=>setF({...f,discount:e.target.value})}/></label><div className="grand"><span>Total</span><strong>{money(tot)}</strong></div><label>Paid Amount <small>(Manual)</small><input type="number" min="0" max={tot} value={f.paid} onChange={e=>setF({...f,paid:e.target.value})}/></label><label>Payment Mode<select value={f.paymentMode} onChange={e=>setF({...f,paymentMode:e.target.value})}><option>Cash</option><option>UPI</option><option>Card</option><option>Other</option></select></label><div><span>Pending</span><strong className={pen>0?"dangerText":"successText"}>{money(pen)}</strong></div><button className="primary savebill" onClick={save}>Save Invoice</button></div>
  <label className="fullfield">Notes<textarea rows="2" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})} placeholder="Optional notes"/></label>
 </section>
}

function Customers(){
 const[d,setD]=useState([]),[q,setQ]=useState(""),[f,setF]=useState({name:"",mobile:"",address:"",notes:""}),[show,setShow]=useState(false),[profile,setProfile]=useState(null),[loading,setLoading]=useState(false);
 const load=()=>api("/customers?q="+encodeURIComponent(q)).then(setD);
 useEffect(load,[]);
 const add=async()=>{if(!f.name.trim())return alert("Name is required");await api("/customers",{method:"POST",body:JSON.stringify(f)});setF({name:"",mobile:"",address:"",notes:""});setShow(false);load()};
 const openProfile=async(id)=>{setLoading(true);try{setProfile(await api("/customers/"+id))}catch(e){alert(e.message)}finally{setLoading(false)}};
 return <section className="panel">
  <div className="toolbar"><div><h2>Customers</h2><p>Customer register, history and pending amounts.</p></div><button className="primary" onClick={()=>setShow(!show)}>＋ Add Customer</button></div>
  {show&&<div className="inlineform"><Field label="Name" value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="Mobile" value={f.mobile} inputMode="numeric" onChange={v=>setF({...f,mobile:v})}/><Field label="Address" value={f.address} onChange={v=>setF({...f,address:v})}/><Field label="Notes" value={f.notes} onChange={v=>setF({...f,notes:v})}/><button className="primary" onClick={add}>Save</button></div>}
  <div className="searchbar"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search name, mobile or customer ID"/><button onClick={load}>Search</button></div>
  <Table h={["ID","Name","Mobile","Address",""]} r={d.map(x=>[x.customerId,x.name,x.mobile||"—",x.address||"—",<button className="primary smallbtn" onClick={()=>openProfile(x._id)}>View</button>])}/>
  {profile&&<CustomerProfile data={profile} close={()=>setProfile(null)}/>} {loading&&<div className="loading">Loading customer…</div>}
 </section>
}

function CustomerProfile({data,close}){
 const c=data.customer||{},tx=data.transactions||[],payments=data.payments||[];
 const total=tx.reduce((a,x)=>a+Number(x.total||0),0),paid=tx.reduce((a,x)=>a+Number(x.paid||0),0),pending=tx.reduce((a,x)=>a+Number(x.pending||0),0);
 const [edit,setEdit]=useState(false),[f,setF]=useState({name:c.name||"",mobile:c.mobile||"",address:c.address||"",notes:c.notes||""});
 const save=async()=>{await api("/customers/"+c._id,{method:"PUT",body:JSON.stringify(f)});location.reload()};
 return <div className="modalback"><div className="modal customerModal"><div className="modalhead"><div><h2>{c.name||"Customer"}</h2><p>{c.customerId} · {c.mobile||"No mobile"}</p></div><button className="iconbtn" onClick={close}>×</button></div>
  <div className="cards small profilecards"><div className="card"><span>Total</span><strong>{money(total)}</strong></div><div className="card"><span>Paid</span><strong className="successText">{money(paid)}</strong></div><div className="card"><span>Pending</span><strong className="dangerText">{money(pending)}</strong></div></div>
  {edit?<div className="inlineform"><Field label="Name" value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="Mobile" value={f.mobile} onChange={v=>setF({...f,mobile:v})}/><Field label="Address" value={f.address} onChange={v=>setF({...f,address:v})}/><Field label="Notes" value={f.notes} onChange={v=>setF({...f,notes:v})}/><button className="primary" onClick={save}>Save Changes</button><button onClick={()=>setEdit(false)}>Cancel</button></div>:<div className="profileinfo"><p><b>Address:</b> {c.address||"—"}</p><p><b>Notes:</b> {c.notes||"—"}</p><button onClick={()=>setEdit(true)}>✎ Edit Customer</button></div>}
  <h3>Transaction History</h3><Table h={["Invoice","Work","Total","Paid","Pending","Date","Receipt"]} r={tx.map(x=>[x.invoiceNo,(x.items||[]).map(i=>i.name).join(", ")||"—",money(x.total),money(x.paid),money(x.pending),new Date(x.createdAt).toLocaleDateString("en-IN"),<button className="smallbtn" onClick={()=>printInvoice(x)}>Print</button>])}/>
  <h3>Payment History</h3><Table h={["Invoice","Amount","Mode","Date"]} r={payments.map(x=>[x.invoiceNo,money(x.amount),x.mode||"Cash",new Date(x.createdAt).toLocaleDateString("en-IN")])}/>
 </div></div>
}

function Services(){const[d,setD]=useState([]),[f,setF]=useState({name:"",category:"",rate:""}),load=()=>api("/services").then(setD);useEffect(load,[]);return <section className="panel"><div className="toolbar"><div><h2>Services</h2><p>Add and manage your service rates.</p></div></div><div className="inlineform"><Field label="Service Name" value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="Category" value={f.category} onChange={v=>setF({...f,category:v})}/><Field label="Rate" type="number" value={f.rate} onChange={v=>setF({...f,rate:v})}/><button className="primary" onClick={async()=>{if(!f.name)return alert("Service name required");await api("/services",{method:"POST",body:JSON.stringify(f)});setF({name:"",category:"",rate:""});load()}}>＋ Add</button></div><Table h={["Name","Category","Rate",""]}r={d.map(x=>[x.name,x.category||"—",money(x.rate),<button className="iconbtn danger" onClick={async()=>{if(confirm("Delete this service?")){await api("/services/"+x._id,{method:"DELETE"});load()}}}>×</button>])}/></section>}

function Payments(){const[d,setD]=useState([]),[h,setH]=useState([]),load=()=>Promise.all([api("/payments/pending"),api("/payments/history")]).then(x=>{setD(x[0]);setH(x[1])});useEffect(load,[]);
 const receive=async x=>{const a=prompt(`Pending: ${money(x.pending)}
Enter amount to receive`);if(a&&Number(a)>0){const mode=prompt("Payment mode (Cash/UPI/Card/Other)","Cash")||"Cash";const updated=await api("/payments/receive",{method:"POST",body:JSON.stringify({invoiceNo:x.invoiceNo,amount:a,mode,operator:"admin"})});load();if(confirm("Payment saved. Print receipt?"))printPaymentReceipt({invoiceNo:updated.invoiceNo,customerName:updated.customerName,amount:Number(a),mode,createdAt:new Date()})}};
 return <><section className="panel"><div className="panelhead"><div><h2>Pending Payments</h2><p>Receive full or partial pending amounts.</p></div><span className="badge dangerBadge">{d.length} pending</span></div><Table h={["Invoice","Customer","Total","Pending",""]} r={d.map(x=>[x.invoiceNo,x.customerName,money(x.total),money(x.pending),<button className="primary smallbtn" onClick={()=>receive(x)}>Receive</button>])}/></section><section className="panel"><div className="panelhead"><div><h2>Payment History</h2><p>Recent collections and receipts.</p></div></div><Table h={["Invoice","Customer","Amount","Mode","Date","Receipt"]} r={h.map(x=>[x.invoiceNo,x.customerName,money(x.amount),x.mode,new Date(x.createdAt).toLocaleDateString("en-IN"),<button className="smallbtn" onClick={()=>printPaymentReceipt(x)}>Print</button>])}/></section></>}

function Expenses(){const[d,setD]=useState([]),[f,setF]=useState({category:"",amount:"",description:"",operator:""}),load=()=>api("/expenses").then(setD);useEffect(load,[]);return <section className="panel"><div className="toolbar"><div><h2>Expenses</h2><p>Track daily business expenses.</p></div></div><div className="inlineform">{Object.keys(f).map(k=><Field key={k} label={k[0].toUpperCase()+k.slice(1)} type={k==="amount"?"number":"text"} value={f[k]} onChange={v=>setF({...f,[k]:v})}/>)}<button className="primary" onClick={async()=>{if(!f.amount)return alert("Amount required");await api("/expenses",{method:"POST",body:JSON.stringify(f)});setF({category:"",amount:"",description:"",operator:""});load()}}>＋ Add Expense</button></div><Table h={["Category","Amount","Description","Operator","Date"]}r={d.map(x=>[x.category||"—",money(x.amount),x.description||"—",x.operator||"—",new Date(x.createdAt).toLocaleDateString("en-IN")])}/></section>}

function Stock(){const[d,setD]=useState([]),[f,setF]=useState({product:"",purchasePrice:0,sellingPrice:0,quantity:0,lowStockAt:5}),[selected,setSelected]=useState(null),[moves,setMoves]=useState([]),load=()=>api("/stock").then(setD);useEffect(load,[]);const movement=async(x,type)=>{const a=prompt(`${type==="IN"?"Stock In":"Stock Out"} — ${x.product}
Current stock: ${x.quantity}
Enter quantity`);if(!a||Number(a)<=0)return;const reason=prompt("Reason",type==="IN"?"Purchase":"Adjustment")||"Manual";try{await api(`/stock/${x._id}/movement`,{method:"POST",body:JSON.stringify({type,quantity:a,reason,operator:"admin"})});load();if(selected?._id===x._id)showHistory(x._id)}catch(e){alert(e.message)}};const showHistory=async(id)=>{const x=d.find(x=>x._id===id)||selected;setSelected(x||null);setMoves(await api(`/stock/${id}/movements`))};return <><section className="panel"><div className="toolbar"><div><h2>Stock</h2><p>Products, Stock In/Out and movement history.</p></div><span className="badge">{d.length} products</span></div><div className="inlineform stockform"><Field label="Product" value={f.product} onChange={v=>setF({...f,product:v})}/><Field label="Purchase Price" type="number" value={f.purchasePrice} onChange={v=>setF({...f,purchasePrice:v})}/><Field label="Selling Price" type="number" value={f.sellingPrice} onChange={v=>setF({...f,sellingPrice:v})}/><Field label="Opening Quantity" type="number" value={f.quantity} onChange={v=>setF({...f,quantity:v})}/><Field label="Low Stock Alert" type="number" value={f.lowStockAt} onChange={v=>setF({...f,lowStockAt:v})}/><button className="primary" onClick={async()=>{if(!f.product)return alert("Product required");await api("/stock",{method:"POST",body:JSON.stringify({...f,operator:"admin"})});setF({product:"",purchasePrice:0,sellingPrice:0,quantity:0,lowStockAt:5});load()}}>＋ Add Product</button></div><Table h={["Product","Purchase","Selling","Qty","Alert","Status","Actions"]}r={d.map(x=>[x.product,money(x.purchasePrice),money(x.sellingPrice),x.quantity,x.lowStockAt,x.quantity<=x.lowStockAt?<span className="badge dangerBadge">Low</span>:<span className="badge successBadge">OK</span>,<div className="stockactions"><button className="smallbtn stockin" onClick={()=>movement(x,"IN")}>＋ In</button><button className="smallbtn stockout" onClick={()=>movement(x,"OUT")}>− Out</button><button className="smallbtn" onClick={()=>showHistory(x._id)}>History</button><button className="iconbtn danger" onClick={async()=>{if(confirm("Delete product?")){await api("/stock/"+x._id,{method:"DELETE"});if(selected?._id===x._id){setSelected(null);setMoves([])}load()}}}>×</button></div>])}/></section>{selected&&<section className="panel"><div className="panelhead"><div><h2>{selected.product} — Movement History</h2><p>Current stock: <b>{d.find(x=>x._id===selected._id)?.quantity??selected.quantity}</b></p></div><button onClick={()=>{setSelected(null);setMoves([])}}>Close</button></div><Table h={["Type","Qty","Reason","Operator","Reference","Date"]} r={moves.map(x=>[x.type==="IN"?<span className="badge successBadge">IN</span>:<span className="badge dangerBadge">OUT</span>,x.quantity,x.reason||"—",x.operator||"—",x.reference||"—",new Date(x.createdAt).toLocaleString("en-IN")])}/></section>}</>}

function Reports(){const[d,setD]=useState(),[range,setRange]=useState({from:"",to:""}),[loading,setLoading]=useState(false);const load=()=>{setLoading(true);api(`/reports${range.from?`?from=${range.from}&to=${range.to||range.from}`:""}`).then(setD).catch(e=>alert(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);const exportXlsx=(data,name)=>{if(!data?.length)return alert("No data");const rows=data.map(x=>{const o={...x};delete o._id;delete o.__v;return o});const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Report");XLSX.writeFile(wb,name)};return <section className="panel"><div className="toolbar"><div><h2>Reports & Export</h2><p>Business performance for the selected period.</p></div><button onClick={load}>{loading?"Loading…":"↻ Refresh"}</button></div><div className="filterbar"><label>From<input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label>To<input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><button className="primary" onClick={load}>Apply</button></div>{d&&<><div className="cards small"><div className="card"><span>Sales</span><strong>{money(d.summary.sales)}</strong></div><div className="card"><span>Collected</span><strong>{money(d.summary.paid)}</strong></div><div className="card"><span>Pending</span><strong>{money(d.summary.pending)}</strong></div><div className="card"><span>Expenses</span><strong>{money(d.summary.expenses)}</strong></div></div><div className="reportgrid"><section className="subpanel"><h3>Operator-wise</h3><Table h={["Operator","Entries","Sales","Paid"]} r={d.operators.map(x=>[x._id,x.entries,money(x.sales),money(x.paid)])}/></section><section className="subpanel"><h3>Payment Mode</h3><Table h={["Mode","Count","Amount"]} r={d.methods.map(x=>[x._id,x.count,money(x.amount)])}/></section><section className="subpanel"><h3>Service / Work-wise</h3><Table h={["Work","Qty","Amount"]} r={d.services.map(x=>[x._id,x.qty,money(x.amount)])}/></section></div><div className="exportgrid"><button onClick={()=>exportXlsx(d.transactions,"transactions.xlsx")}>↓ Transactions Excel</button><button onClick={()=>exportXlsx(d.payments,"payments.xlsx")}>↓ Payments Excel</button><button onClick={()=>exportXlsx(d.expenses,"expenses.xlsx")}>↓ Expenses Excel</button><button onClick={()=>exportXlsx(d.operators,"operator-report.xlsx")}>↓ Operator Report</button></div></>}</section>}
function Field({label,value,onChange,type="text",inputMode}){return <label className="field">{label}<input type={type} inputMode={inputMode} value={value??""} onChange={e=>onChange(e.target.value)}/></label>}
function Table({h,r}){return <div className="table"><table><thead><tr>{h.map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{r.length?r.map((row,i)=><tr key={i}>{row.map((y,j)=><td key={j} data-label={h[j]}>{y}</td>)}</tr>):<tr><td className="empty" colSpan={h.length}>No records found</td></tr>}</tbody></table></div>}
function Loading(){return <div className="loading"><div className="spinner"/>Loading…</div>}
function printPaymentReceipt(x){const w=window.open("","_blank","width=500,height=700");if(!w)return;w.document.write(`<html><head><title>Payment Receipt ${x.invoiceNo}</title><style>body{font-family:Arial;padding:25px;max-width:420px;margin:auto;color:#111}h1{text-align:center;margin:0 0 4px}.sub{text-align:center;color:#666;margin-bottom:25px}.row{display:flex;justify-content:space-between;border-bottom:1px dashed #bbb;padding:10px 0}.amount{font-size:25px;font-weight:bold;text-align:center;padding:18px 0}@media print{body{padding:8mm}}</style></head><body><h1>Abhi Online Center</h1><div class="sub">Payment Receipt</div><div class="row"><span>Invoice</span><b>${x.invoiceNo||"—"}</b></div><div class="row"><span>Customer</span><b>${x.customerName||"—"}</b></div><div class="amount">${money(x.amount)}</div><div class="row"><span>Mode</span><b>${x.mode||"Cash"}</b></div><div class="row"><span>Date</span><b>${new Date(x.createdAt||Date.now()).toLocaleString("en-IN")}</b></div><p style="text-align:center;margin-top:30px">Thank you</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
function printInvoice(x,format="a4"){const thermal=format==="thermal";const w=window.open("","_blank",thermal?"width=420,height=700":"width=900,height=900");if(!w)return;const width=thermal?"72mm":"210mm";const pad=thermal?"5mm":"14mm";w.document.write(`<html><head><title>${x.invoiceNo}</title><style>@page{size:${thermal?"80mm auto":"A4"};margin:0}body{font-family:Arial,sans-serif;width:${width};box-sizing:border-box;padding:${pad};margin:auto;color:#111;font-size:${thermal?"11px":"13px"}}h1{text-align:center;font-size:${thermal?"18px":"24px"};margin:0 0 4px}.muted{color:#666}.center{text-align:center}.line{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px ${thermal?"dashed":"solid"} #ddd}.total{font-size:${thermal?"15px":"20px"};font-weight:bold;margin-top:8px}.items{margin-top:12px}.thank{text-align:center;margin-top:22px}@media print{body{width:${width};padding:${pad}}}</style></head><body><h1>Abhi Online Center</h1><div class="center muted">${thermal?"Payment Invoice":"Invoice"} · ${x.invoiceNo}</div><p>Customer: <b>${x.customerName||"—"}</b><br>Mobile: ${x.mobile||"—"}<br>Date: ${new Date(x.createdAt||Date.now()).toLocaleString("en-IN")}</p><div class="items">${(x.items||[]).map(i=>`<div class="line"><span>${i.name} × ${i.quantity}</span><b>${money(i.amount)}</b></div>`).join("")}</div><div class="line">Subtotal <b>${money(x.subtotal)}</b></div><div class="line">Discount <b>${money(x.discount)}</b></div><div class="line total">Total <span>${money(x.total)}</span></div><div class="line">Paid <b>${money(x.paid)}</b></div><div class="line">Pending <b>${money(x.pending)}</b></div><div class="line">Payment <b>${x.paymentMode||"—"}</b></div><p class="thank muted">Thank you for your business</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
createRoot(document.getElementById("root")).render(<App/>);
