import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import mongoose from "mongoose";
import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";
import path from "path";
import {fileURLToPath} from "url";
dotenv.config();
const app=express(),PORT=process.env.PORT||5000,SECRET=process.env.JWT_SECRET||"change-me";
app.use(cors());app.use(express.json());
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const customerSchema=new mongoose.Schema({customerId:{type:String,unique:true,index:true},name:{type:String,required:true},mobile:String,address:String,notes:String},{timestamps:true});
const serviceSchema=new mongoose.Schema({name:{type:String,required:true},category:String,rate:Number,active:{type:Boolean,default:true}},{timestamps:true});
const txSchema=new mongoose.Schema({invoiceNo:{type:String,unique:true,index:true},customer:mongoose.Schema.Types.ObjectId,customerName:String,mobile:String,operator:String,items:[{name:String,type:String,quantity:Number,rate:Number,amount:Number}],subtotal:Number,discount:Number,total:Number,paid:Number,pending:Number,paymentMode:String,status:String,notes:String},{timestamps:true});
const paymentSchema=new mongoose.Schema({invoiceNo:String,customerName:String,amount:Number,mode:String,operator:String,notes:String},{timestamps:true});
const expenseSchema=new mongoose.Schema({category:String,amount:Number,description:String,operator:String},{timestamps:true});
const stockSchema=new mongoose.Schema({product:String,purchasePrice:Number,sellingPrice:Number,quantity:Number,lowStockAt:{type:Number,default:5}},{timestamps:true});
const Customer=mongoose.model("Customer",customerSchema),Service=mongoose.model("Service",serviceSchema),Transaction=mongoose.model("Transaction",txSchema),Payment=mongoose.model("Payment",paymentSchema),Expense=mongoose.model("Expense",expenseSchema),Stock=mongoose.model("Stock",stockSchema);
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{return res.status(401).json({message:"Login required"})}}
async function nextNo(Model,field,prefix){const x=await Model.findOne({[field]:{$regex:"^"+prefix}}).sort({createdAt:-1});const n=x?Number(String(x[field]).replace(/\D/g,""))+1:1;return prefix+String(n).padStart(6,"0")}
app.get("/api/health",(q,r)=>r.json({ok:true,app:"Abhi Online Center V3"}));
app.post("/api/login",async(req,res)=>{const good=req.body.username===(process.env.ADMIN_USERNAME||"admin");const configured=process.env.ADMIN_PASSWORD||"change-this-password";let pass=false;try{pass=configured.startsWith("$2")?await bcrypt.compare(req.body.password||"",configured):String(req.body.password||"")===configured}catch{}if(!good||!pass)return res.status(401).json({message:"Invalid username or password"});res.json({token:jwt.sign({username:req.body.username,role:"admin"},SECRET,{expiresIn:"7d"}),user:{username:req.body.username,role:"admin"}})});
app.get("/api/dashboard",auth,async(req,res)=>{const d=new Date();d.setHours(0,0,0,0);const [s,e,p,l]=await Promise.all([Transaction.aggregate([{$match:{createdAt:{$gte:d}}},{$group:{_id:null,total:{$sum:"$total"},paid:{$sum:"$paid"}}}]),Expense.aggregate([{$match:{createdAt:{$gte:d}}},{$group:{_id:null,total:{$sum:"$amount"}}}]),Transaction.aggregate([{$match:{pending:{$gt:0}}},{$group:{_id:null,total:{$sum:"$pending"}}}]),Stock.find({$expr:{$lte:["$quantity","$lowStockAt"]}}).limit(10)]);res.json({todaySale:s[0]?.total||0,todayCollection:s[0]?.paid||0,todayExpenses:e[0]?.total||0,pending:p[0]?.total||0,todayEntries:await Transaction.countDocuments({createdAt:{$gte:d}}),netCollection:(s[0]?.paid||0)-(e[0]?.total||0),lowStock:l})});
app.get("/api/customers",auth,async(req,res)=>{const q=(req.query.q||"").trim();const f=q?{$or:[{name:{$regex:q,$options:"i"}},{mobile:{$regex:q,$options:"i"}},{customerId:{$regex:q,$options:"i"}}]}:{};res.json(await Customer.find(f).sort({createdAt:-1}).limit(300))});
app.post("/api/customers",auth,async(req,res)=>res.status(201).json(await Customer.create({...req.body,customerId:await nextNo(Customer,"customerId","CUS")})));
app.get("/api/services",auth,async(req,res)=>res.json(await Service.find().sort({name:1})));
app.post("/api/services",auth,async(req,res)=>res.status(201).json(await Service.create(req.body)));
app.delete("/api/services/:id",auth,async(req,res)=>{await Service.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.post("/api/transactions",auth,async(req,res)=>{const b=req.body,items=(b.items||[]).map(x=>({...x,quantity:Number(x.quantity)||1,rate:Number(x.rate)||0,amount:(Number(x.quantity)||1)*(Number(x.rate)||0)})),subtotal=items.reduce((a,x)=>a+x.amount,0),discount=Math.max(0,Number(b.discount)||0),total=Math.max(0,subtotal-discount),paid=Math.min(total,Math.max(0,Number(b.paid)||0)),pending=total-paid,invoiceNo=await nextNo(Transaction,"invoiceNo","INV");let c=await Customer.findOne({mobile:b.mobile});if(!c&&b.customerName)c=await Customer.create({customerId:await nextNo(Customer,"customerId","CUS"),name:b.customerName,mobile:b.mobile});const tx=await Transaction.create({invoiceNo,customer:c?._id,customerName:b.customerName,mobile:b.mobile,operator:b.operator,items,subtotal,discount,total,paid,pending,paymentMode:b.paymentMode,status:pending?"Pending":"Paid",notes:b.notes});if(paid)await Payment.create({invoiceNo,customerName:b.customerName,amount:paid,mode:b.paymentMode,operator:b.operator,notes:"Initial payment"});res.status(201).json(tx)});
app.get("/api/transactions",auth,async(req,res)=>res.json(await Transaction.find().sort({createdAt:-1}).limit(300)));
app.get("/api/payments/pending",auth,async(req,res)=>res.json(await Transaction.find({pending:{$gt:0}}).sort({createdAt:-1})));
app.get("/api/payments/history",auth,async(req,res)=>res.json(await Payment.find().sort({createdAt:-1}).limit(300)));
app.post("/api/payments/receive",auth,async(req,res)=>{const x=await Transaction.findOne({invoiceNo:req.body.invoiceNo});if(!x)return res.status(404).json({message:"Invoice not found"});const n=Math.min(Math.max(0,Number(req.body.amount)||0),x.pending);x.paid+=n;x.pending=x.total-x.paid;x.status=x.pending?"Pending":"Paid";await x.save();if(n)await Payment.create({invoiceNo:x.invoiceNo,customerName:x.customerName,amount:n,mode:req.body.mode||"Cash",operator:req.body.operator||"admin",notes:req.body.notes});res.json(x)});
app.get("/api/expenses",auth,async(req,res)=>res.json(await Expense.find().sort({createdAt:-1}).limit(300)));
app.post("/api/expenses",auth,async(req,res)=>res.status(201).json(await Expense.create({...req.body,amount:Number(req.body.amount)||0})));
app.get("/api/stock",auth,async(req,res)=>res.json(await Stock.find().sort({product:1})));
app.post("/api/stock",auth,async(req,res)=>res.status(201).json(await Stock.create({...req.body,quantity:Number(req.body.quantity)||0})));
app.put("/api/stock/:id",auth,async(req,res)=>res.json(await Stock.findByIdAndUpdate(req.params.id,req.body,{new:true})));
app.delete("/api/stock/:id",auth,async(req,res)=>{await Stock.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.get("/api/reports",auth,async(req,res)=>{const from=req.query.from?new Date(req.query.from):new Date(new Date().setHours(0,0,0,0)),to=req.query.to?new Date(req.query.to):new Date();to.setHours(23,59,59,999);const [transactions,expenses,payments]=await Promise.all([Transaction.find({createdAt:{$gte:from,$lte:to}}).sort({createdAt:-1}),Expense.find({createdAt:{$gte:from,$lte:to}}),Payment.find({createdAt:{$gte:from,$lte:to}})]);res.json({transactions,expenses,payments})});
const dist=path.join(__dirname,"..","client","dist");app.use(express.static(dist));app.get(/^(?!\/api)/,(q,r)=>r.sendFile(path.join(dist,"index.html")));
if(process.env.MONGODB_URI)mongoose.connect(process.env.MONGODB_URI).then(()=>app.listen(PORT,()=>console.log("Abhi Online Center V3 on "+PORT))).catch(e=>{console.error(e);process.exit(1)});else console.log("Set MONGODB_URI in .env before starting.");
